# This is a sample of how your database.yml file should be setup, 
# but with your own user credentials of your local setup.
# After you're done modifying this file to mirror setup, save this as database.yml

common: &common
  adapter: postgresql
  username: postgres
  password: OnlyDestiny8
  host: localhost
  port: 5432

development:
  <<: *common
  database: hearst_development

test:
  <<: *common
  database: hearst_test

production:
  <<: *common
  database: hearst_production