development:
  adapter: postgresql
  encoding: utf8
  database: castfb_development
  pool: 5
  username: ubuntu
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: castfb_test
  pool: 5
  username: ubuntu
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: castfb_production
  pool: 5
  username: ubuntu
  password: 