common: &common
  adapter: postgresql
  username: postgres
  password: OnlyDestiny8
  host: localhost
  port: 5432

development:
  <<: *common
  database: hearst_development

test:
  <<: *common
  database: hearst_test

production:
  <<: *common
  database: hearst_production